 <#
    # 8-old

    Let's have our method accept parameters
  #>

$Method = @'

    public static void myMethod( string message )
    {
        // https://docs.microsoft.com/dotnet/api/system.windows.forms.messagebox
        System.Windows.Forms.MessageBox.Show( message );
    }
'@

$TypeParam = @{

    MemberDefinition     = $Method
    Name                 = 'myType08'
    ReferencedAssemblies = 'System.Windows.Forms.dll'
}
Add-Type @TypeParam

 <# 
    Now we've created another type, named “Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.myType08”

    If we call our static method, we'll have the code run, and we'll see an actual message box!
  #>

[Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.myType08]::myMethod( 'This is a new message!' )