using System;
using System.Runtime.InteropServices;
using Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class AdjustTokenPrivilegesClass03
    {
    
            [DllImport(
                "advapi32.dll",
             // CharSet       = CharSet.Unicode,
                ExactSpelling = true,
                SetLastError  = true
            )]

         // https://docs.microsoft.com/windows/win32/api/securitybaseapi/nf-securitybaseapi-adjusttokenprivileges
            public   static extern bool AdjustTokenPrivileges(  // works
         // internal static extern bool AdjustTokenPrivileges(  // fails with 
                IntPtr TokenHandle,
                bool   DisableAllPrivileges,

             // ref TOKEN_PRIVILEGES NewState,
             // ref Object       NewState,   // does not generate any errors but does not have effect either. The privilege remains disabled.
             // ref TokPriv1Luid NewState,   // works, if defined in the same block of code
             // ref Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.TokPriv1LuidClass+TokPriv1Luid"    NewState,
             // ref TokPriv1LuidClass01+TokPriv1Luid                                                            NewState,   // "Identifier expected"
             // ref Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.TokPriv1LuidClass01+TokPriv1Luid   NewState,   // "Identifier expected"
             // ref TokPriv1LuidClass06                NewState,   // Cannot find type
                ref TokPriv1LuidClass07                NewState,
                
             // UInt32 BufferLengthInBytes,
                int    BufferLength,                
             // ref TOKEN_PRIVILEGES PreviousState,
                IntPtr PreviousState,   
             // out UInt32 ReturnLengthInBytes);
                IntPtr ReturnLength
            );

         // [StructLayout(LayoutKind.Sequential, Pack = 1)]
         // public   class  TokPriv1Luid    // fails with “The parameter is incorrect”
         // public   struct TokPriv1Luid    // works but with warning "The generated type defines no public methods or properties."
         // internal struct TokPriv1Luid    // fails with "parameter type 'ref Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.AdjustTokenPrivilegesClass.TokPriv1Luid' is less accessible than method "
         // {
         //     public int  Count;
         //     public long Luid;
         //     public int  Attr;
         // }

    }

}
