using System;
using System.Runtime.InteropServices;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class TokPriv1LuidClass05
    {
                [StructLayout(LayoutKind.Sequential, Pack = 1)]
            public   class  TokPriv1Luid
         // public   struct TokPriv1Luid    // works
         // internal struct TokPriv1Luid
            {
                public int  Count;
                public long Luid;
                public int  Attr;
            }

    }

}
