using System;
using System.Runtime.InteropServices;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class TokPriv1LuidClass11
    {
    
 // using System;
 // using System.Runtime.InteropServices;

    namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
    {
        [System.Runtime.InteropServices.StructLayout(
            System.Runtime.InteropServices.LayoutKind.Sequential,
            Pack = 1
        )]
        public struct TokPriv1LuidStruct11
        {
            public int  Count;
            public long Luid;
            public int  Attr;
        }
    }

    }

}
