
 // using System;
 // using System.Runtime.InteropServices;

    namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
    {
        [StructLayout(LayoutKind.Sequential, Pack = 1)]
        public struct TokPriv1LuidStruct01
        {
                public int  Count;
                public long Luid;
                public int  Attr;
        }
    }