using System;
using System.Runtime.InteropServices;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class AdjustTokenPrivilege
    {
    
                [DllImport(
                    "advapi32.dll",
                    CharSet       = CharSet.Unicode,
                    ExactSpelling = true,
                    SetLastError  = true
                )]

             // https://docs.microsoft.com/windows/win32/api/securitybaseapi/nf-securitybaseapi-adjusttokenprivileges
                public static extern bool  AdjustTokenPrivileges(
                    IntPtr                                                                        TokenHandle,
                    bool                                                                          DisableAllPrivileges,
                    ref  Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.TokenPrivilege  NewState,
                    int                                                                           BufferLength,
                    IntPtr                                                                        PreviousState,
                    IntPtr                                                                        ReturnLength
                );

    }

}
