using System;
using System.Runtime.InteropServices;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class OpenProcessTokenClass
    {
    
            [DllImport(
                "advapi32.dll",
                CharSet       = CharSet.Unicode,
                ExactSpelling = true,
                SetLastError  = true
            )]
            public static extern bool OpenProcessToken(
                IntPtr ProcessHandle,
                Int32  DesiredAccess,
                ref IntPtr TokenHandle
            );

    }

}
