using System;
using System.Runtime.InteropServices;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class TokPriv1LuidClass08
    {
                public int  Count;
            public long Luid;
            public int  Attr;

    }

}
