using System;
using System.Runtime.InteropServices;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class LookupPrivilegeValueClass
    {
    
            [DllImport(
                "advapi32.dll",
                CharSet       = CharSet.Unicode,
                ExactSpelling = true,
                SetLastError  = true
            )]
            public static extern bool LookupPrivilegeValueW(
                string lpSystemName,
                string lpName,
                ref long lpLuid
            );

    }

}
