 <#
    5. Creating a public class

    Now let's do the same thing, but mark our class as “Public” so that we can
    explore its properties.
  #>

$code = @'

    public class myType05
    {    
        // we will add some code here
    }
'@

$TypeParam = @{

    TypeDefinition     = $Code
}
Add-Type @TypeParam

 <#
    Note that we have not specified a namespace, and therefore the class is 
   “orphaned” or stand-alone. In other words, it does not have a fully-qualified 
    name like “Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.myType03”.

    But we can see that the class is now indeed Public, and the same default
    constructor member. With which we can create an instance of this class.
  #>
  
[myType05].IsPublic

[myType05].DeclaredMembers

$myInstance05 = [myType05]::new()