 <#
    41. Making a method public
    
    To make our method visible in PowerShell, we need to explicitly declare it as “Public”

    Because by default, it was created as “Private” which is not very helpful for our scenario.

    (Remember, we want to call the c# code from PowerShell.)
  #>

$path = '.\41.cs'

Get-Content -Path $path

$TypeParam = @{
    Path     = $path
}
Add-Type @TypeParam

 <# 
    We have created “Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes.myType05” type.

    Now if we explore its methods, we'll find our method again, but this time it's public.
  #>

[Pronichkin.Sample.myType41].DeclaredMethods[0].IsPrivate
[Pronichkin.Sample.myType41].DeclaredMethods[0].IsPublic

 <#
    What this actually means is we can now call this method from PowerShell.
    
    But to do this, we first need to create an instance of the type.
  #>

$myInstance41 = [Pronichkin.Sample.myType41]::new()

 <#
    And now we can finally called the method like this.
  #>

$myInstance41.MyMethod()

 <#
    Even though the method does nothign so far, the syntax looks like familiar PowerShell.
  #>