using System;
using System.Runtime.InteropServices;

namespace Microsoft.PowerShell.Commands.AddType.AutoGeneratedTypes
{
    public class myType09b
    {
    
    public static System.Windows.Forms.DialogResult myMethod( string message )
    {
        // https://docs.microsoft.com/dotnet/api/system.windows.forms.messagebox
        return System.Windows.Forms.MessageBox.Show( message );
    }

    }

}
