#
# Module manifest for module 'DatacenterAdvancedAutomation.Selenium'
#
# Generated by: artem@pronichkin.com
#
# Generated on: 8/21/2019
#

@{

  # Script module or binary module file associated with this manifest.
  # RootModule = ''

  # Version number of this module.
    ModuleVersion = '1.0.2021.0707'

  # Supported psEditions
    CompatiblepsEditions = 'Desktop'

  # ID used to uniquely identify this module
    GUID = '67b9101b-d119-4691-9231-92972c617ef6'

  # Author of this module
    Author = 'artem@pronichkin.com'

  # Company or vendor of this module
    CompanyName = 'Artem Pronichkin'

  # Copyright statement for this module
    Copyright = 'Artem Pronichkin. All rights reserved.'

  # Description of the functionality provided by this module
    Description = 'Datacenter Advanced Automation Selenium'

  # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1.0.0'

  # Name of the Windows PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the Windows PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # CLRVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        'DatacenterAdvancedAutomation.Utility'
    )

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  # ScriptsToProcess = @()

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
    
        'Get-swdAssembly.psm1'
        'Get-swdBrowser.psm1'
        'Get-swdService.psm1'
        'Start-swdService.psm1'
        'Stop-swdService.psm1'
    )

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(

        'Get-swdAssembly'
        'Get-swdBrowser'
        'Get-swdService'
        'Start-swdService'
        'Stop-swdService'
    )

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

  # Variables to export from this module
    VariablesToExport = '*'

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

  # DSC resources to export from this module
  # DscResourcesToExport = @()

  # List of all modules packaged with this module
    ModuleList = @(

        @{  ModuleName    = 'Get-swdAssembly'                       ;   ModuleVersion = '1.0.2021.0707'  }
        @{  ModuleName    = 'Get-swdBrowser'                        ;   ModuleVersion = '1.0.2021.0707'  }
        @{  ModuleName    = 'Get-swdService'                        ;   ModuleVersion = '1.0.2021.0707'  }
        @{  ModuleName    = 'Start-swdService'                      ;   ModuleVersion = '1.0.2021.0707'  }
        @{  ModuleName    = 'Stop-swdService'                       ;   ModuleVersion = '1.0.2021.0707'  }
    )

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a psData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        psData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of psData hashtable

    } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''
}